### ISSUE TITLE
Why are raw counts so large?

### ISSUE THREAD

**Issue by davidwhogg** [davidwhogg/OWL#1]
Is there a big DC offset being added to the counts?  In this star (KIC 3335426) all the pixel values (raw) are around 4e5, but the noise demonstrates that there are truly FAR MORE COUNTS hitting the bright pixels.  This can't be a sky level, because then the fainter pixels would be less noisy relative to the brighter pixels.  Etc.  I guess this is all in the data handbook?

**Comment by dfm** [comment]
Take a look at page 23 of the [Kepler Archive manual](https://archive.stsci.edu/kepler/manuals/archive_manual.pdf). I only vaguely understand all the words there.

**Comment by mrtommyb** [comment]
Is the difference between e-/s and e- per integration?

**Comment by davidwhogg** [comment]
No it is a DC offset issue; something about "To restore the values contained in this column to the Analog to Digital Units read off the photometer, subtract the appropriate “fixed offset”, LC or SC (keywords LCFXDOFF and SCFXDOFF), and add the mean black level (keyword MEANBLCK) times the number of readouts (keyword NREADOUT). Then, each count represents one Analog to Digital Unit."

**Comment by davidwhogg** [comment]
this is all cool but no longer a necessary-to-solve issue; closing
