### ISSUE TITLE
give unto Hogg some more Kepler examples

### ISSUE THREAD

**Issue by davidwhogg** [davidwhogg/OWL#10]
He wants (a) a G star with a transiting exoplanet, probably around 3-10 Earth radii, so it is visible in the OWL photometry.

He wants (b) a star with substantial intrinsic variability, best of all due to stellar rotation.

**Comment by davidwhogg** [comment]
@dfm pingy pingy

**Comment by dfm** [comment]
For (a) you could try @mrtommyb's favourite Kepler-69 (KIC 8692861), or he might have a better suggestion.

For (b) try @RuthAngus' favourite KIC 3223000, or she might have a better suggestion.

**Comment by RuthAngus** [comment]
My new fave: KIC 10295224

**Comment by davidwhogg** [comment]
Dudes, reopening.

Both 3223000 and 10295224 are saturated.

Can I get also non-saturated examples of same?  The OWL is sucking on saturated stars.

**Comment by davidwhogg** [comment]
ping

**Comment by RuthAngus** [comment]
Try 1026474 and 1872885
