### ISSUE TITLE
How to go from `raw_cnts` to SAP flux?

### ISSUE THREAD

**Issue by davidwhogg** [davidwhogg/OWL#2]
@dfm you claim that if you co-add the raw_cnts you get the SAP fluxes; what _exactly_ do you do?  Pseudo-code or actual code preferred to prose.  CC @mrtommyb

**Comment by dfm** [comment]
That's not very easy but here's a snippet that will help:

```
# ...
with tpf.open() as hdu:
    table = hdu[1].data
    mask = hdu[2].data
bkg_sub_flux = table["FLUX"]
sap = np.sum(bkg_sub_flux[:, mask==3], axis=1)

# Compare...
with client.light_curves(kicid, sci_data_quarter=5)[0].open() as hdu:
    data = hdu[1].data["SAP_FLUX"]

print(sap - data)
```

**Comment by davidwhogg** [comment]
Cool!  I will use the "FLUX" column for now until I have reasons to do otherwise.

**Comment by mrtommyb** [comment]
I may be wrong here but I think FLUX has been cosmic ray ‘corrected’.
I can check fairly quickly if it would be useful.

Tom

**Comment by dfm** [comment]
That's right it has been "corrected". It becomes _exactly_ SAP if you sum
FLUX over the optimal aperture.

On Sun, Mar 9, 2014 at 2:17 PM, Tom Barclay notifications@github.comwrote:

> I wrong be off here but I think FLUX has been cosmic ray 'corrected' <-
> made much worse.
> I can check fairly quickly if it would be useful.
> 
> Tom
> 
> On Mar 9, 2014, at 8:12 AM, David W. Hogg notifications@github.com
> wrote:
> 
> > Cool! I will use the "FLUX" column for now until I have reasons to do
> > otherwise.
> > 
> > ## 
> > 
> > Reply to this email directly or view it on GitHub.
> 
> ## 
> 
> Reply to this email directly or view it on GitHubhttps://github.com/davidwhogg/HLM/issues/2#issuecomment-37133845
> .

## 

Dan Foreman-Mackey
http://dan.iel.fm

**Comment by mrtommyb** [comment]
You may want to consider putting the 'cosmic rays' back in.

**Comment by davidwhogg** [comment]
Yes, we do want to put the CRs back in; is there any _easy_ way to do that?

**Comment by davidwhogg** [comment]
for now I am closing this "wontfix" but this is a to-do for the next round of awesome.
