### ISSUE TITLE
kplr doesn't work with astropy

### ISSUE THREAD

**Issue by davidwhogg** [davidwhogg/OWL#3]
Maybe I am being stupid.

I have astropy installed; `import astropy` works.

But `kplr` fails saying

```
Traceback (most recent call last):
  File "hlm.py", line 79, in <module>
    with tpf.open() as hdu:
  File "/Library/Python/2.7/site-packages/kplr/api.py", line 629, in open
    raise ImportError("The pyfits module is required to read data "
ImportError: The pyfits module is required to read data files.
```

I assume I am being a dunce, but do I _also_ have to install pyfits, even though it is all inside astropy?  Or what?

**Comment by dfm** [comment]
You should open this as an issue on `kplr`. `pyfits` is now called `astropy.io.fits` apparently. I can fix this issue.

**Comment by davidwhogg** [comment]
This is fixed
